### ISSUE TITLE
Miui 13

### ISSUE THREAD

**Issue by kohanla** [Asicosilomu/app-pinning-helper-for-miui#1]
Great idea! Thanks for that.

Unfortunately it does not work. This is what happens in my case:

When clicking the button in the "floating app", the device activates the lockscreen. After that I can see an "app pinned" toast message, and "three seconds" later an "app unpinned" toast message.

**Comment by Asicosilomu** [comment]
You need to have a lock screen (PIN, Pattern or password) set. It won't work without one.

**Comment by kohanla** [comment]
Yes, I do have a password/lockscreen. See also my previous answer.

**Comment by Asicosilomu** [comment]
What version of MIUI do you have (like what subversion, e.g. 13.0.10.0)? Are you using Gesture navigation? Are MIUI optimizations on?

**Comment by kohanla** [comment]
13.0.10 

Navigation buttons are enabled.

Miui optimizations are on. Do I have to disable them for that feature?

**Comment by Asicosilomu** [comment]
Sounds good. You even know about the optimizations.

Well, I've had them off not long after getting my device, as an app required it. Optimizations were off for the entire development and still are. Apart from that your MIUI version is identical to mine.

Optimizations are probably the issue here. You can try disabling them and trying again.

If that fixes the issue, I'll add a warning about it in the app.

**Comment by Asicosilomu** [comment]
There's probably a soft block for the app pinning that gets disabled with the optimizations. Not sure though.

**Comment by kohanla** [comment]
Ok, thanks.

**Comment by kohanla** [comment]
I disabled optimizations, but then floating windows do not work anymore unfortunately.

Maybe you could also do the reverse test?

**Comment by Asicosilomu** [comment]
Works for me even without optimizations.

**Comment by Asicosilomu** [comment]
What is a reverse test?

**Comment by kohanla** [comment]
> What is a reverse test?

Turn on optimizations to confirm whether this is an optimizations issue.

**Comment by Asicosilomu** [comment]
Apart from deleting all my home screen icons (I use Sense beta launcher), resetting my custom DPI setting and fucking with the permissions, it didn't affect the app at all. May be something else I have enabled.

**Comment by kohanla** [comment]
Ok. Thanks for your time!
